import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "../globals.css";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <header className="flex justify-between p-8 pt-4 pb-0">
          <Image src="/Logo-Educa-L-cor.svg" width={172} height={24} alt="" />
          <div className="flex gap-x-2 items-center">
            <Button variant={"default"} className="px-8 rounded-2xl">
              Home
            </Button>
            <Button variant={"default"} className="px-8 rounded-2xl">
              Sobre
            </Button>
            <Button
              variant={"secondary"}
              className="px-8 shadow shadow-black rounded-2xl bg-educa-primary"
            >
              Entrar
            </Button>
          </div>
        </header>

        <main className="flex-1 px-20 pb-8 overflow-hidden flex items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
